---
- name: Terminate WP cluster
  hosts:
    - tag_Class_wpserver
  connection: local
  gather_facts: false
  tasks:
    - name: Terminate all WP machines
      ec2:
        state: 'absent'
        region: '{{ ec2_region }}'
        instance_ids: '{{ ec2_id }}'
