- name: Scale up policy
  ec2_scaling_policy:
    state: present
    region: us-west-2
    name: "scaleup-policy"
    adjustment_type: "ChangeInCapacity"
    asg_name: "myasg"
    scaling_adjustment: "+1"
    min_adjustment_step: 1
    cooldown: 30
  register: "scale_up_policy"

- name: Scale down policy
  ec2_scaling_policy:
    state: present
    region: us-west-2
    name: "scaledown-policy"
    adjustment_type: "ChangeInCapacity"
    asg_name: "myasg"
    scaling_adjustment: "-1"
    min_adjustment_step: 1
    cooldown: 120
  register: "scale_down_policy"



- name: Create CPU utilization metric alarm
  ec2_metric_alarm:
    state: present
    region: us-west-2
    namespace: "AWS/EC2"
    name: "cpu-utilization"
    metric: "CPUUtilization"
    statistic: Average
    comparison: ">="
    threshold: 3.0
    unit: "Percent"
    period: 60
    evaluation_periods: 2
    dimensions:
      AutoScalingGroupName: "myasg"
    alarm_actions:
     "{{ scale_up_policy.arn }}"

- name: Create CPU utilization metric alarm
  ec2_metric_alarm:
    state: present
    region: us-west-2
    namespace: "AWS/EC2"
    name: "cpu-utilization2"
    metric: "CPUUtilization"
    statistic: Average
    comparison: "<="
    threshold: 1.0
    unit: "Percent"
    period: 60
    evaluation_periods: 2
    dimensions:
      AutoScalingGroupName: "myasg"
    alarm_actions:
      "{{ scale_down_policy.arn }}"


