---
- name: Stopping group
  ec2_asg:
        name: myasg
        launch_config_name: my_new_lc3
        health_check_period: 60
        health_check_type: ELB
        replace_all_instances: yes
        min_size: 0
        max_size: 0
        state: absent
        desired_capacity: 0
        region: us-west-2
        vpc_zone_identifier: [ 'subnet-6eb40118' ]
