--- 
- name: Provision and configure Auto-scaling group
  ec2_lc:
        name: my_new_lc_4
        image_id: ami-57844537
        key_name: gl-test2
        instance_monitoring: True
        region: us-west-2
        security_groups: sg-74b51512
        instance_type: t2.micro
        state: present

    
- name: Starting group
  ec2_asg:
        name: myasg
        launch_config_name: my_new_lc_4
        load_balancers: gllb
        health_check_period: 60
        health_check_type: ELB
        replace_all_instances: yes
        min_size: 1
        max_size: 5
        desired_capacity: 1
        region: us-west-2
        vpc_zone_identifier: 'subnet-6eb40118'
        tags:
          - group: asg1


