---
- name: Provision and configure a WordPress cluster on AWS
  hosts: localhost
  connection: local
  gather_facts: True

  vars_files:
    - vars/mysql.yml

  tasks:
    - name: Starting Proxy machine
      local_action:
        module: ec2
        image: "{{ IMAGE }}"
        instance_type: "{{ INSTANCE_TYPE }}"
        keypair: "{{ KEYPAIR }}"
        region: "{{ EC2_REGION }}"
        group_id: "{{ NODE_SECURITY_GROUP }}"
        vpc_subnet_id: "{{ SUBNET_SEED }}"
        assign_public_ip: yes
        instance_tags:
          Name: ha
          Role: proxy
          Class: wpserver
        count: 1
        volumes:
        - device_name: /dev/sda1
          device_type: "{{VOL_TYPE }}"
          volume_size: "{{ VOL_SIZE }}"
          delete_on_termination: true
        wait: yes
      register: ec2

    - name: Wait for SSH to come up
      wait_for: host={{ item.private_ip }} port=22 delay=60 timeout=900 state=started
      with_items: '{{ec2.instances}}'


#    - name: Add ip to wp-workers
#      add_host:
#        groupname: "wp-workers"
#        hostname: "{{ item.private_ip }}"
#        with_items: '{{ec2.instances}}'i


    - name: Add new instance to host group
      local_action: add_host hostname={{ item.private_ip }} groupname=proxy
      with_items: ec2.instances

- name: Apply wp role
#  hosts: proxy
  hosts: tag_Name_ha
  user: "{{ REMOTE_USER }}"
  sudo: True

  gather_facts: True
  vars:
    LISTEN_ON: ":80"
    haproxy_backend_servers:
      - name: app1
        address: "{{ hostvars[inventory_hostname].groups.tag_Name_wpserver[0]+':80'}}"
      - name: app2
        address: "{{ hostvars[inventory_hostname].groups.tag_Name_wpserver[0]+':80'}}"
 


  vars_files:
    - vars/proxy.yml
  roles:
    - { role: kevincoakley.haproxy }
  tags:
    - haproxy


