---
- name: Provision and configure a WordPress cluster on AWS
  hosts: localhost
  connection: local
  gather_facts: True

  vars_files:
    - vars/mysql.yml

  tasks:
    - name: Starting WP machines
      local_action:
        module: ec2
        image: "{{ IMAGE }}"
        instance_type: "{{ INSTANCE_TYPE }}"
        keypair: "{{ KEYPAIR }}"
        region: "{{ EC2_REGION }}"
        group_id: "{{ NODE_SECURITY_GROUP }}"
        vpc_subnet_id: "{{ SUBNET_SEED }}"
        assign_public_ip: yes
        instance_tags:
          Name: wpserver
          Role: worker
          Class: wpserver
        count: 2
        volumes:
        - device_name: /dev/sda1
          device_type: "{{VOL_TYPE }}"
          volume_size: "{{ VOL_SIZE }}"
          delete_on_termination: true
        wait: yes
      register: ec2

    - name: Wait for SSH to come up
      wait_for: host={{ item.private_ip }} port=22 delay=60 timeout=900 state=started
      with_items: '{{ec2.instances}}'


#    - name: Add ip to wp-workers
#      add_host:
#        groupname: "wp-workers"
#        hostname: "{{ item.private_ip }}"
#        with_items: '{{ec2.instances}}'i


    - name: Add new instance to host group
      local_action: add_host hostname={{ item.private_ip }} groupname=workers
      with_items: ec2.instances

- name: Apply wp role
  hosts: workers
  user: "{{ REMOTE_USER }}"
  gather_facts: True
  vars_files:
  - vars/mysql.yml
  sudo: True
  vars:
    wp_version: 4.0
    wp_install_dir: '/var/www/awesome_wordpress_site'
    wp_db_name: 'wpdb'
    wp_db_user: 'wpuser'
    wp_db_password: 'wppass'
    wp_db_host: "{{ mysql_ip }}"
    wp_apache_hostname: 'local.dev'
    wp_apache_alias: 'localhost'
    wp_apache_admin_email: 'admin@example.com'
  pre_tasks:
  - include: tasks/epel.yml

  roles:
  - { role: geerlingguy.apache }
  - { role: geerlingguy.php }
  - { role: darthwade.wordpress-apache, mysql_ip: 192.168.1.119 }

  post_tasks:
  - include: task/selinux.yml


