--- 
- name: Provision and configure a WordPress cluster on AWS
  hosts: localhost
  connection: local
  gather_facts: True

  vars_files:
    - vars/mysql.yml
    
  tasks:
    - name: Starting MYSQL machine
      local_action:
        module: ec2
        image: "{{ IMAGE }}"
        instance_type: "{{ INSTANCE_TYPE }}"
        keypair: "{{ KEYPAIR }}"
        region: "{{ EC2_REGION }}"
        group_id: "{{ NODE_SECURITY_GROUP }}"
        vpc_subnet_id: "{{ SUBNET_SEED }}"
        assign_public_ip: yes
        instance_tags:
          Name: "{{ TAG_NAME }}"
          Role: mysql
          Class: wpserver
        count: 1
        volumes:
          - device_name: /dev/sda1
            device_type: "{{VOL_TYPE }}"
            volume_size: "{{ VOL_SIZE }}"
            delete_on_termination: true
        wait: yes
      register: ec2

    - debug: var=ec2.instances[0].private_ip


    - name: Wait for SSH to come up
      wait_for: host={{ item.private_ip }} port=22 delay=60 timeout=900 state=started
      with_items: '{{ec2.instances}}'

    - name: Add new instance to host group
      local_action: add_host hostname={{ item.private_ip }} groupname=launched
      with_items: ec2.instances


    - name: Set MySQL ip address as fact
      set_fact: mysql_ip="{{ ec2.instances[0].private_ip }}"


    - name: Add mysql to mysql_private
      add_host:
        groupname: "mysql_private"
        hostname: "{{ ec2.instances[0].private_ip }}"

    - debug: var=hostvars['localhost'].mysql_ip
#    - name: Launch HAProxy machine
#      local_action:
#        module: ec2
#        image: "{{ IMAGE }}"
#        instance_type: "{{ INSTANCE_TYPE }}"
#        keypair: "{{ KEYPAIR }}"
#        region: "{{ EC2_REGION }}"
#        group_id: "{{ NODE_SECURITY_GROUP }}"
#        vpc_subnet_id: "{{ SUBNET_SEED }}"
#        assign_public_ip: yes
#        instance_tags:
#          Name: Proxy
#          Role: HAProxy
#          Class: wpserver
#        count: 0
#        volumes:
#          - device_name: /dev/sda1
#            device_type: "{{ VOL_TYPE }}"
#            volume_size: "{{ VOL_SIZE }}"
#            delete_on_termination: true
#        wait: yes
#      register: ec2
#
#    - name: Add HAProxy to haproxy_private
#      add_host:
#        groupname: "haproxy_private"
#        hostname: "{{ ec2.instances[0].private_ip }}"
#
#    - name: Add HAProxy to haproxy_public
#      add_host:
#        groupname: "haproxy_public"
#        hostname: "{{ ec2.instances[0].public_ip }}"
#
    - name: Starting WP machines
      local_action:
        module: ec2
        image: "{{ IMAGE }}"
        instance_type: "{{ INSTANCE_TYPE }}"
        keypair: "{{ KEYPAIR }}"
        region: "{{ EC2_REGION }}"
        group_id: "{{ NODE_SECURITY_GROUP }}"
        vpc_subnet_id: "{{ SUBNET_SEED }}"
        assign_public_ip: yes
        instance_tags:
          Name: wpserver
          Role: worker
          Class: wpserver
        count: 2
        volumes:
          - device_name: /dev/sda1
            device_type: "{{VOL_TYPE }}"
            volume_size: "{{ VOL_SIZE }}"
            delete_on_termination: true
        wait: yes
      register: ec2

    - name: Wait for SSH to come up
      wait_for: host={{ item.private_ip }} port=22 delay=60 timeout=900 state=started
      with_items: '{{ec2.instances}}'


    - name: Add private addresses ip to wp_private
      add_host:
        groupname: "wp_private"
        hostname: "{{ item.private_ip }}"
      with_items: "{{ ec2.instances }}"

- name: Apply mysql role
  hosts: mysql_private
  user: "{{ REMOTE_USER }}"
  gather_facts: True
  sudo: True

  vars_files:
    - vars/mysql.yml
  roles:
  - { role: geerlingguy.mysql }

- name: Apply wp role
  hosts: wp_private
  user: "{{ REMOTE_USER }}"
  gather_facts: True
  vars_files:
  - vars/mysql.yml
  sudo: True
  vars:
    wp_version: 4.0
    wp_install_dir: '/var/www/awesome_wordpress_site'
    wp_db_name: 'wpdb'
    wp_db_user: 'wpuser'
    wp_db_password: 'wppass'
    wp_db_host: "{{ hostvars['localhost'].mysql_ip }}"
    wp_apache_hostname: 'local.dev'
    wp_apache_alias: 'localhost'
    wp_apache_admin_email: 'admin@example.com'
  pre_tasks:
  - include: tasks/epel.yml

  roles:
  - { role: geerlingguy.apache }
  - { role: geerlingguy.php }
  - { role: darthwade.wordpress-apache }
